/*
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.11.1
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onesignal.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.onesignal.client.JSON;

/**
 * Request context at the time of the event. Absent if context was not captured.
 */
@ApiModel(description = "Request context at the time of the event. Absent if context was not captured.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AuditLogContext {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  private String country;

  public static final String SERIALIZED_NAME_IP = "ip";
  @SerializedName(SERIALIZED_NAME_IP)
  private String ip;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private Object metadata;

  public static final String SERIALIZED_NAME_USER_AGENT = "user_agent";
  @SerializedName(SERIALIZED_NAME_USER_AGENT)
  private String userAgent;

  public AuditLogContext() { 
  }

  public AuditLogContext country(String country) {
    
    this.country = country;
    return this;
  }

   /**
   * Country code derived from the request IP.
   * @return country
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Country code derived from the request IP.")

  public String getCountry() {
    return country;
  }


  public void setCountry(String country) {
    this.country = country;
  }


  public AuditLogContext ip(String ip) {
    
    this.ip = ip;
    return this;
  }

   /**
   * IP address the request originated from.
   * @return ip
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "IP address the request originated from.")

  public String getIp() {
    return ip;
  }


  public void setIp(String ip) {
    this.ip = ip;
  }


  public AuditLogContext metadata(Object metadata) {
    
    this.metadata = metadata;
    return this;
  }

   /**
   * Additional context-specific data.
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Additional context-specific data.")

  public Object getMetadata() {
    return metadata;
  }


  public void setMetadata(Object metadata) {
    this.metadata = metadata;
  }


  public AuditLogContext userAgent(String userAgent) {
    
    this.userAgent = userAgent;
    return this;
  }

   /**
   * User agent of the client that made the request.
   * @return userAgent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "User agent of the client that made the request.")

  public String getUserAgent() {
    return userAgent;
  }


  public void setUserAgent(String userAgent) {
    this.userAgent = userAgent;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuditLogContext auditLogContext = (AuditLogContext) o;
    return Objects.equals(this.country, auditLogContext.country) &&
        Objects.equals(this.ip, auditLogContext.ip) &&
        Objects.equals(this.metadata, auditLogContext.metadata) &&
        Objects.equals(this.userAgent, auditLogContext.userAgent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, ip, metadata, userAgent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuditLogContext {\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    userAgent: ").append(toIndentedString(userAgent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("country");
    openapiFields.add("ip");
    openapiFields.add("metadata");
    openapiFields.add("user_agent");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AuditLogContext.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AuditLogContext' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AuditLogContext> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AuditLogContext.class));

       return (TypeAdapter<T>) new TypeAdapter<AuditLogContext>() {
           @Override
           public void write(JsonWriter out, AuditLogContext value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AuditLogContext read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();

             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AuditLogContext given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AuditLogContext
  * @throws IOException if the JSON string is invalid with respect to AuditLogContext
  */
  public static AuditLogContext fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AuditLogContext.class);
  }

 /**
  * Convert an instance of AuditLogContext to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

