/*
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.11.0
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onesignal.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.onesignal.client.JSON;

/**
 * A resource the action was performed on.
 */
@ApiModel(description = "A resource the action was performed on.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AuditLogTarget {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private Object metadata;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public AuditLogTarget() { 
  }

  public AuditLogTarget id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * UUID of the resource.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "UUID of the resource.")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public AuditLogTarget metadata(Object metadata) {
    
    this.metadata = metadata;
    return this;
  }

   /**
   * Additional resource-specific data.
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Additional resource-specific data.")

  public Object getMetadata() {
    return metadata;
  }


  public void setMetadata(Object metadata) {
    this.metadata = metadata;
  }


  public AuditLogTarget name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Display name of the resource. Absent if unavailable.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Display name of the resource. Absent if unavailable.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public AuditLogTarget type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Resource type (e.g. notification, segment, journey, app).
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Resource type (e.g. notification, segment, journey, app).")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuditLogTarget auditLogTarget = (AuditLogTarget) o;
    return Objects.equals(this.id, auditLogTarget.id) &&
        Objects.equals(this.metadata, auditLogTarget.metadata) &&
        Objects.equals(this.name, auditLogTarget.name) &&
        Objects.equals(this.type, auditLogTarget.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, metadata, name, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuditLogTarget {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("metadata");
    openapiFields.add("name");
    openapiFields.add("type");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AuditLogTarget.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AuditLogTarget' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AuditLogTarget> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AuditLogTarget.class));

       return (TypeAdapter<T>) new TypeAdapter<AuditLogTarget>() {
           @Override
           public void write(JsonWriter out, AuditLogTarget value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AuditLogTarget read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();

             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AuditLogTarget given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AuditLogTarget
  * @throws IOException if the JSON string is invalid with respect to AuditLogTarget
  */
  public static AuditLogTarget fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AuditLogTarget.class);
  }

 /**
  * Convert an instance of AuditLogTarget to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

