/*
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onesignal.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.onesignal.client.model.AuditLogActor;
import com.onesignal.client.model.AuditLogContext;
import com.onesignal.client.model.AuditLogTarget;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.onesignal.client.JSON;

/**
 * AuditLogEvent
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AuditLogEvent {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ACTION = "action";
  @SerializedName(SERIALIZED_NAME_ACTION)
  private String action;

  public static final String SERIALIZED_NAME_ACTOR = "actor";
  @SerializedName(SERIALIZED_NAME_ACTOR)
  private AuditLogActor actor;

  public static final String SERIALIZED_NAME_APP_ID = "app_id";
  @SerializedName(SERIALIZED_NAME_APP_ID)
  private String appId;

  public static final String SERIALIZED_NAME_CONTEXT = "context";
  @SerializedName(SERIALIZED_NAME_CONTEXT)
  private AuditLogContext context;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private Object metadata;

  public static final String SERIALIZED_NAME_OCCURRED_AT = "occurred_at";
  @SerializedName(SERIALIZED_NAME_OCCURRED_AT)
  private String occurredAt;

  public static final String SERIALIZED_NAME_ORGANIZATION_ID = "organization_id";
  @SerializedName(SERIALIZED_NAME_ORGANIZATION_ID)
  private String organizationId;

  public static final String SERIALIZED_NAME_TARGETS = "targets";
  @SerializedName(SERIALIZED_NAME_TARGETS)
  private List<AuditLogTarget> targets = null;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private Integer version;

  public AuditLogEvent() { 
  }

  public AuditLogEvent action(String action) {
    
    this.action = action;
    return this;
  }

   /**
   * The action that was performed (e.g. notification.sent, segment.created, member.invited).
   * @return action
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The action that was performed (e.g. notification.sent, segment.created, member.invited).")

  public String getAction() {
    return action;
  }


  public void setAction(String action) {
    this.action = action;
  }


  public AuditLogEvent actor(AuditLogActor actor) {
    
    this.actor = actor;
    return this;
  }

   /**
   * Get actor
   * @return actor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AuditLogActor getActor() {
    return actor;
  }


  public void setActor(AuditLogActor actor) {
    this.actor = actor;
  }


  public AuditLogEvent appId(String appId) {
    
    this.appId = appId;
    return this;
  }

   /**
   * UUID of the app the event is associated with. Absent for org-level events.
   * @return appId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "UUID of the app the event is associated with. Absent for org-level events.")

  public String getAppId() {
    return appId;
  }


  public void setAppId(String appId) {
    this.appId = appId;
  }


  public AuditLogEvent context(AuditLogContext context) {
    
    this.context = context;
    return this;
  }

   /**
   * Get context
   * @return context
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AuditLogContext getContext() {
    return context;
  }


  public void setContext(AuditLogContext context) {
    this.context = context;
  }


  public AuditLogEvent id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * UUID of the audit log event.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "UUID of the audit log event.")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public AuditLogEvent metadata(Object metadata) {
    
    this.metadata = metadata;
    return this;
  }

   /**
   * Additional event-specific data that does not fit into the standard fields.
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Additional event-specific data that does not fit into the standard fields.")

  public Object getMetadata() {
    return metadata;
  }


  public void setMetadata(Object metadata) {
    this.metadata = metadata;
  }


  public AuditLogEvent occurredAt(String occurredAt) {
    
    this.occurredAt = occurredAt;
    return this;
  }

   /**
   * RFC 3339 timestamp of when the event occurred (e.g. 2026-02-18T12:34:56Z).
   * @return occurredAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "RFC 3339 timestamp of when the event occurred (e.g. 2026-02-18T12:34:56Z).")

  public String getOccurredAt() {
    return occurredAt;
  }


  public void setOccurredAt(String occurredAt) {
    this.occurredAt = occurredAt;
  }


  public AuditLogEvent organizationId(String organizationId) {
    
    this.organizationId = organizationId;
    return this;
  }

   /**
   * UUID of the organization the event belongs to.
   * @return organizationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "UUID of the organization the event belongs to.")

  public String getOrganizationId() {
    return organizationId;
  }


  public void setOrganizationId(String organizationId) {
    this.organizationId = organizationId;
  }


  public AuditLogEvent targets(List<AuditLogTarget> targets) {
    
    this.targets = targets;
    return this;
  }

  public AuditLogEvent addTargetsItem(AuditLogTarget targetsItem) {
    if (this.targets == null) {
      this.targets = new ArrayList<>();
    }
    this.targets.add(targetsItem);
    return this;
  }

   /**
   * The resources the action was performed on. May be empty for org-level events.
   * @return targets
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The resources the action was performed on. May be empty for org-level events.")

  public List<AuditLogTarget> getTargets() {
    return targets;
  }


  public void setTargets(List<AuditLogTarget> targets) {
    this.targets = targets;
  }


  public AuditLogEvent version(Integer version) {
    
    this.version = version;
    return this;
  }

   /**
   * Schema version of the event payload.
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Schema version of the event payload.")

  public Integer getVersion() {
    return version;
  }


  public void setVersion(Integer version) {
    this.version = version;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuditLogEvent auditLogEvent = (AuditLogEvent) o;
    return Objects.equals(this.action, auditLogEvent.action) &&
        Objects.equals(this.actor, auditLogEvent.actor) &&
        Objects.equals(this.appId, auditLogEvent.appId) &&
        Objects.equals(this.context, auditLogEvent.context) &&
        Objects.equals(this.id, auditLogEvent.id) &&
        Objects.equals(this.metadata, auditLogEvent.metadata) &&
        Objects.equals(this.occurredAt, auditLogEvent.occurredAt) &&
        Objects.equals(this.organizationId, auditLogEvent.organizationId) &&
        Objects.equals(this.targets, auditLogEvent.targets) &&
        Objects.equals(this.version, auditLogEvent.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, actor, appId, context, id, metadata, occurredAt, organizationId, targets, version);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuditLogEvent {\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    actor: ").append(toIndentedString(actor)).append("\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    occurredAt: ").append(toIndentedString(occurredAt)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    targets: ").append(toIndentedString(targets)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("action");
    openapiFields.add("actor");
    openapiFields.add("app_id");
    openapiFields.add("context");
    openapiFields.add("id");
    openapiFields.add("metadata");
    openapiFields.add("occurred_at");
    openapiFields.add("organization_id");
    openapiFields.add("targets");
    openapiFields.add("version");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AuditLogEvent.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AuditLogEvent' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AuditLogEvent> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AuditLogEvent.class));

       return (TypeAdapter<T>) new TypeAdapter<AuditLogEvent>() {
           @Override
           public void write(JsonWriter out, AuditLogEvent value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AuditLogEvent read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();

             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AuditLogEvent given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AuditLogEvent
  * @throws IOException if the JSON string is invalid with respect to AuditLogEvent
  */
  public static AuditLogEvent fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AuditLogEvent.class);
  }

 /**
  * Convert an instance of AuditLogEvent to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

