/*
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onesignal.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.onesignal.client.model.DuplicateJourneyOverrides;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.onesignal.client.JSON;

/**
 * Optional body for Duplicate journey. Only overrides is applied. A journey field sent at the top level is ignored.
 */
@ApiModel(description = "Optional body for Duplicate journey. Only overrides is applied. A journey field sent at the top level is ignored.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class DuplicateJourneyRequest {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_OVERRIDES = "overrides";
  @SerializedName(SERIALIZED_NAME_OVERRIDES)
  private DuplicateJourneyOverrides overrides;

  public DuplicateJourneyRequest() { 
  }

  public DuplicateJourneyRequest overrides(DuplicateJourneyOverrides overrides) {
    
    this.overrides = overrides;
    return this;
  }

   /**
   * Get overrides
   * @return overrides
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DuplicateJourneyOverrides getOverrides() {
    return overrides;
  }


  public void setOverrides(DuplicateJourneyOverrides overrides) {
    this.overrides = overrides;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DuplicateJourneyRequest duplicateJourneyRequest = (DuplicateJourneyRequest) o;
    return Objects.equals(this.overrides, duplicateJourneyRequest.overrides);
  }

  @Override
  public int hashCode() {
    return Objects.hash(overrides);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DuplicateJourneyRequest {\n");
    sb.append("    overrides: ").append(toIndentedString(overrides)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("overrides");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DuplicateJourneyRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DuplicateJourneyRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DuplicateJourneyRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DuplicateJourneyRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<DuplicateJourneyRequest>() {
           @Override
           public void write(JsonWriter out, DuplicateJourneyRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DuplicateJourneyRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();

             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DuplicateJourneyRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DuplicateJourneyRequest
  * @throws IOException if the JSON string is invalid with respect to DuplicateJourneyRequest
  */
  public static DuplicateJourneyRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DuplicateJourneyRequest.class);
  }

 /**
  * Convert an instance of DuplicateJourneyRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

