/*
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onesignal.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.onesignal.client.model.EmailReputationWindow;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.onesignal.client.JSON;

/**
 * App-wide email bounce and spam complaint rates, broken out by time window. &#x60;last_24_hours&#x60;, &#x60;last_7_days&#x60;, and &#x60;last_30_days&#x60; each hold the bounce and complaint rates for email delivered in that window.
 */
@ApiModel(description = "App-wide email bounce and spam complaint rates, broken out by time window. `last_24_hours`, `last_7_days`, and `last_30_days` each hold the bounce and complaint rates for email delivered in that window.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class EmailReputationResponse {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_LAST24_HOURS = "last_24_hours";
  @SerializedName(SERIALIZED_NAME_LAST24_HOURS)
  private EmailReputationWindow last24Hours;

  public static final String SERIALIZED_NAME_LAST7_DAYS = "last_7_days";
  @SerializedName(SERIALIZED_NAME_LAST7_DAYS)
  private EmailReputationWindow last7Days;

  public static final String SERIALIZED_NAME_LAST30_DAYS = "last_30_days";
  @SerializedName(SERIALIZED_NAME_LAST30_DAYS)
  private EmailReputationWindow last30Days;

  public EmailReputationResponse() { 
  }

  public EmailReputationResponse last24Hours(EmailReputationWindow last24Hours) {
    
    this.last24Hours = last24Hours;
    return this;
  }

   /**
   * Get last24Hours
   * @return last24Hours
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EmailReputationWindow getLast24Hours() {
    return last24Hours;
  }


  public void setLast24Hours(EmailReputationWindow last24Hours) {
    this.last24Hours = last24Hours;
  }


  public EmailReputationResponse last7Days(EmailReputationWindow last7Days) {
    
    this.last7Days = last7Days;
    return this;
  }

   /**
   * Get last7Days
   * @return last7Days
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EmailReputationWindow getLast7Days() {
    return last7Days;
  }


  public void setLast7Days(EmailReputationWindow last7Days) {
    this.last7Days = last7Days;
  }


  public EmailReputationResponse last30Days(EmailReputationWindow last30Days) {
    
    this.last30Days = last30Days;
    return this;
  }

   /**
   * Get last30Days
   * @return last30Days
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EmailReputationWindow getLast30Days() {
    return last30Days;
  }


  public void setLast30Days(EmailReputationWindow last30Days) {
    this.last30Days = last30Days;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmailReputationResponse emailReputationResponse = (EmailReputationResponse) o;
    return Objects.equals(this.last24Hours, emailReputationResponse.last24Hours) &&
        Objects.equals(this.last7Days, emailReputationResponse.last7Days) &&
        Objects.equals(this.last30Days, emailReputationResponse.last30Days);
  }

  @Override
  public int hashCode() {
    return Objects.hash(last24Hours, last7Days, last30Days);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmailReputationResponse {\n");
    sb.append("    last24Hours: ").append(toIndentedString(last24Hours)).append("\n");
    sb.append("    last7Days: ").append(toIndentedString(last7Days)).append("\n");
    sb.append("    last30Days: ").append(toIndentedString(last30Days)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("last_24_hours");
    openapiFields.add("last_7_days");
    openapiFields.add("last_30_days");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EmailReputationResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EmailReputationResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EmailReputationResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EmailReputationResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<EmailReputationResponse>() {
           @Override
           public void write(JsonWriter out, EmailReputationResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EmailReputationResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();

             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EmailReputationResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EmailReputationResponse
  * @throws IOException if the JSON string is invalid with respect to EmailReputationResponse
  */
  public static EmailReputationResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EmailReputationResponse.class);
  }

 /**
  * Convert an instance of EmailReputationResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

