/*
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onesignal.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.onesignal.client.model.EstimateNotificationRecipientsRequestAllOf;
import com.onesignal.client.model.FilterExpression;
import com.onesignal.client.model.SegmentNotificationTarget;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.onesignal.client.JSON;

/**
 * The targeting subset of notification fields this endpoint honors. &#x60;included_segments&#x60; (or its &#x60;\&quot;All\&quot;&#x60; shorthand) is required. &#x60;excluded_segments&#x60;, &#x60;filters&#x60;, &#x60;include_aliases&#x60;, and &#x60;target_channel&#x60; narrow that segment-based audience further when present. Use &#x60;target_channel&#x60; to select which platforms to count. Other notification targeting fields (&#x60;include_subscription_ids&#x60; and the other raw subscription id/token fields, and the individual &#x60;isIos&#x60; / &#x60;isAndroid&#x60; / etc. platform flags) are not read by this endpoint. All non-targeting notification fields (content, delivery options, and so on) are accepted, but ignored. 
 */
@ApiModel(description = "The targeting subset of notification fields this endpoint honors. `included_segments` (or its `\"All\"` shorthand) is required. `excluded_segments`, `filters`, `include_aliases`, and `target_channel` narrow that segment-based audience further when present. Use `target_channel` to select which platforms to count. Other notification targeting fields (`include_subscription_ids` and the other raw subscription id/token fields, and the individual `isIos` / `isAndroid` / etc. platform flags) are not read by this endpoint. All non-targeting notification fields (content, delivery options, and so on) are accepted, but ignored. ")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class EstimateNotificationRecipientsRequest {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_INCLUDED_SEGMENTS = "included_segments";
  @SerializedName(SERIALIZED_NAME_INCLUDED_SEGMENTS)
  private List<String> includedSegments = null;

  public static final String SERIALIZED_NAME_EXCLUDED_SEGMENTS = "excluded_segments";
  @SerializedName(SERIALIZED_NAME_EXCLUDED_SEGMENTS)
  private List<String> excludedSegments = null;

  public static final String SERIALIZED_NAME_APP_ID = "app_id";
  @SerializedName(SERIALIZED_NAME_APP_ID)
  private String appId;

  public static final String SERIALIZED_NAME_FILTERS = "filters";
  @SerializedName(SERIALIZED_NAME_FILTERS)
  private List<FilterExpression> filters = null;

  public static final String SERIALIZED_NAME_INCLUDE_ALIASES = "include_aliases";
  @SerializedName(SERIALIZED_NAME_INCLUDE_ALIASES)
  private Map<String, List<String>> includeAliases = null;

  /**
   * Which platforms to count recipients for. Selects the same default platforms Create notification would use for the channel. Individual platform flags (&#x60;isIos&#x60;, &#x60;isAndroid&#x60;, etc.) are not supported by this endpoint.
   */
  @JsonAdapter(TargetChannelEnum.Adapter.class)
  public enum TargetChannelEnum {
    PUSH("push"),
    
    EMAIL("email"),
    
    SMS("sms");

    private String value;

    TargetChannelEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TargetChannelEnum fromValue(String value) {
      for (TargetChannelEnum b : TargetChannelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TargetChannelEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TargetChannelEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TargetChannelEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TargetChannelEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TARGET_CHANNEL = "target_channel";
  @SerializedName(SERIALIZED_NAME_TARGET_CHANNEL)
  private TargetChannelEnum targetChannel;

  public EstimateNotificationRecipientsRequest() { 
  }

  public EstimateNotificationRecipientsRequest includedSegments(List<String> includedSegments) {
    
    this.includedSegments = includedSegments;
    return this;
  }

  public EstimateNotificationRecipientsRequest addIncludedSegmentsItem(String includedSegmentsItem) {
    if (this.includedSegments == null) {
      this.includedSegments = new ArrayList<>();
    }
    this.includedSegments.add(includedSegmentsItem);
    return this;
  }

   /**
   * The segment names you want to target. Users in these segments will receive a notification. This targeting parameter is only compatible with excluded_segments. Example: [\&quot;Active Users\&quot;, \&quot;Inactive Users\&quot;] &#x60;\&quot;All\&quot;&#x60; is a shorthand for every subscribed user: if the array includes the string &#x60;\&quot;All\&quot;&#x60; and the app has no segment actually named &#x60;All&#x60;, it targets all subscribers instead of a literal segment lookup. 
   * @return includedSegments
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The segment names you want to target. Users in these segments will receive a notification. This targeting parameter is only compatible with excluded_segments. Example: [\"Active Users\", \"Inactive Users\"] `\"All\"` is a shorthand for every subscribed user: if the array includes the string `\"All\"` and the app has no segment actually named `All`, it targets all subscribers instead of a literal segment lookup. ")

  public List<String> getIncludedSegments() {
    return includedSegments;
  }


  public void setIncludedSegments(List<String> includedSegments) {
    this.includedSegments = includedSegments;
  }


  public EstimateNotificationRecipientsRequest excludedSegments(List<String> excludedSegments) {
    
    this.excludedSegments = excludedSegments;
    return this;
  }

  public EstimateNotificationRecipientsRequest addExcludedSegmentsItem(String excludedSegmentsItem) {
    if (this.excludedSegments == null) {
      this.excludedSegments = new ArrayList<>();
    }
    this.excludedSegments.add(excludedSegmentsItem);
    return this;
  }

   /**
   * Segment that will be excluded when sending. Users in these segments will not receive a notification, even if they were included in included_segments. This targeting parameter is only compatible with included_segments. Example: [\&quot;Active Users\&quot;, \&quot;Inactive Users\&quot;] 
   * @return excludedSegments
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Segment that will be excluded when sending. Users in these segments will not receive a notification, even if they were included in included_segments. This targeting parameter is only compatible with included_segments. Example: [\"Active Users\", \"Inactive Users\"] ")

  public List<String> getExcludedSegments() {
    return excludedSegments;
  }


  public void setExcludedSegments(List<String> excludedSegments) {
    this.excludedSegments = excludedSegments;
  }


  public EstimateNotificationRecipientsRequest appId(String appId) {
    
    this.appId = appId;
    return this;
  }

   /**
   * The OneSignal App ID for your app, which can be found in Keys &amp; IDs.
   * @return appId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The OneSignal App ID for your app, which can be found in Keys & IDs.")

  public String getAppId() {
    return appId;
  }


  public void setAppId(String appId) {
    this.appId = appId;
  }


  public EstimateNotificationRecipientsRequest filters(List<FilterExpression> filters) {
    
    this.filters = filters;
    return this;
  }

  public EstimateNotificationRecipientsRequest addFiltersItem(FilterExpression filtersItem) {
    if (this.filters == null) {
      this.filters = new ArrayList<>();
    }
    this.filters.add(filtersItem);
    return this;
  }

   /**
   * Get filters
   * @return filters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<FilterExpression> getFilters() {
    return filters;
  }


  public void setFilters(List<FilterExpression> filters) {
    this.filters = filters;
  }


  public EstimateNotificationRecipientsRequest includeAliases(Map<String, List<String>> includeAliases) {
    
    this.includeAliases = includeAliases;
    return this;
  }

  public EstimateNotificationRecipientsRequest putIncludeAliasesItem(String key, List<String> includeAliasesItem) {
    if (this.includeAliases == null) {
      this.includeAliases = new HashMap<>();
    }
    this.includeAliases.put(key, includeAliasesItem);
    return this;
  }

   /**
   * Target specific users by aliases assigned via API. An alias can be an external_id, onesignal_id, or a custom alias. Accepts an object where keys are alias labels and values are arrays of alias IDs to include Example usage: { \&quot;external_id\&quot;: [\&quot;exId1\&quot;, \&quot;extId2\&quot;], \&quot;internal_label\&quot;: [\&quot;id1\&quot;, \&quot;id2\&quot;] } Keys must match API spellings exactly (for example the label for External ID is the string &#x60;external_id&#x60;; arbitrary keys such as camelCase variants are not aliases and may yield no recipients). Not compatible with any other targeting parameters. REQUIRED: REST API Key Authentication Limit of 2,000 entries per REST API call Note: If targeting push, email, or sms subscribers with same ids, use with target_channel to indicate you are sending a push or email or sms.
   * @return includeAliases
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Target specific users by aliases assigned via API. An alias can be an external_id, onesignal_id, or a custom alias. Accepts an object where keys are alias labels and values are arrays of alias IDs to include Example usage: { \"external_id\": [\"exId1\", \"extId2\"], \"internal_label\": [\"id1\", \"id2\"] } Keys must match API spellings exactly (for example the label for External ID is the string `external_id`; arbitrary keys such as camelCase variants are not aliases and may yield no recipients). Not compatible with any other targeting parameters. REQUIRED: REST API Key Authentication Limit of 2,000 entries per REST API call Note: If targeting push, email, or sms subscribers with same ids, use with target_channel to indicate you are sending a push or email or sms.")

  public Map<String, List<String>> getIncludeAliases() {
    return includeAliases;
  }


  public void setIncludeAliases(Map<String, List<String>> includeAliases) {
    this.includeAliases = includeAliases;
  }


  public EstimateNotificationRecipientsRequest targetChannel(TargetChannelEnum targetChannel) {
    
    this.targetChannel = targetChannel;
    return this;
  }

   /**
   * Which platforms to count recipients for. Selects the same default platforms Create notification would use for the channel. Individual platform flags (&#x60;isIos&#x60;, &#x60;isAndroid&#x60;, etc.) are not supported by this endpoint.
   * @return targetChannel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Which platforms to count recipients for. Selects the same default platforms Create notification would use for the channel. Individual platform flags (`isIos`, `isAndroid`, etc.) are not supported by this endpoint.")

  public TargetChannelEnum getTargetChannel() {
    return targetChannel;
  }


  public void setTargetChannel(TargetChannelEnum targetChannel) {
    this.targetChannel = targetChannel;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EstimateNotificationRecipientsRequest estimateNotificationRecipientsRequest = (EstimateNotificationRecipientsRequest) o;
    return Objects.equals(this.includedSegments, estimateNotificationRecipientsRequest.includedSegments) &&
        Objects.equals(this.excludedSegments, estimateNotificationRecipientsRequest.excludedSegments) &&
        Objects.equals(this.appId, estimateNotificationRecipientsRequest.appId) &&
        Objects.equals(this.filters, estimateNotificationRecipientsRequest.filters) &&
        Objects.equals(this.includeAliases, estimateNotificationRecipientsRequest.includeAliases) &&
        Objects.equals(this.targetChannel, estimateNotificationRecipientsRequest.targetChannel);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(includedSegments, excludedSegments, appId, filters, includeAliases, targetChannel);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EstimateNotificationRecipientsRequest {\n");
    sb.append("    includedSegments: ").append(toIndentedString(includedSegments)).append("\n");
    sb.append("    excludedSegments: ").append(toIndentedString(excludedSegments)).append("\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    includeAliases: ").append(toIndentedString(includeAliases)).append("\n");
    sb.append("    targetChannel: ").append(toIndentedString(targetChannel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("included_segments");
    openapiFields.add("excluded_segments");
    openapiFields.add("app_id");
    openapiFields.add("filters");
    openapiFields.add("include_aliases");
    openapiFields.add("target_channel");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("app_id");
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EstimateNotificationRecipientsRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EstimateNotificationRecipientsRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EstimateNotificationRecipientsRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EstimateNotificationRecipientsRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<EstimateNotificationRecipientsRequest>() {
           @Override
           public void write(JsonWriter out, EstimateNotificationRecipientsRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EstimateNotificationRecipientsRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();

             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EstimateNotificationRecipientsRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EstimateNotificationRecipientsRequest
  * @throws IOException if the JSON string is invalid with respect to EstimateNotificationRecipientsRequest
  */
  public static EstimateNotificationRecipientsRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EstimateNotificationRecipientsRequest.class);
  }

 /**
  * Convert an instance of EstimateNotificationRecipientsRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

