/*
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.0.1
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onesignal.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.onesignal.client.JSON;

/**
 * ExportSubscriptionsRequestBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-13T23:45:41.211Z[Etc/UTC]")
public class ExportSubscriptionsRequestBody {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_EXTRA_FIELDS = "extra_fields";
  @SerializedName(SERIALIZED_NAME_EXTRA_FIELDS)
  private List<String> extraFields = null;

  public static final String SERIALIZED_NAME_LAST_ACTIVE_SINCE = "last_active_since";
  @SerializedName(SERIALIZED_NAME_LAST_ACTIVE_SINCE)
  private String lastActiveSince;

  public static final String SERIALIZED_NAME_SEGMENT_NAME = "segment_name";
  @SerializedName(SERIALIZED_NAME_SEGMENT_NAME)
  private String segmentName;

  public ExportSubscriptionsRequestBody() { 
  }

  public ExportSubscriptionsRequestBody extraFields(List<String> extraFields) {
    
    this.extraFields = extraFields;
    return this;
  }

  public ExportSubscriptionsRequestBody addExtraFieldsItem(String extraFieldsItem) {
    if (this.extraFields == null) {
      this.extraFields = new ArrayList<>();
    }
    this.extraFields.add(extraFieldsItem);
    return this;
  }

   /**
   * Additional fields that you wish to include. Currently supports location, country, rooted, notification_types, ip, external_user_id, web_auth, and web_p256.
   * @return extraFields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Additional fields that you wish to include. Currently supports location, country, rooted, notification_types, ip, external_user_id, web_auth, and web_p256.")

  public List<String> getExtraFields() {
    return extraFields;
  }


  public void setExtraFields(List<String> extraFields) {
    this.extraFields = extraFields;
  }


  public ExportSubscriptionsRequestBody lastActiveSince(String lastActiveSince) {
    
    this.lastActiveSince = lastActiveSince;
    return this;
  }

   /**
   * Export all devices with a last_active timestamp greater than this time.  Unixtime in seconds.
   * @return lastActiveSince
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Export all devices with a last_active timestamp greater than this time.  Unixtime in seconds.")

  public String getLastActiveSince() {
    return lastActiveSince;
  }


  public void setLastActiveSince(String lastActiveSince) {
    this.lastActiveSince = lastActiveSince;
  }


  public ExportSubscriptionsRequestBody segmentName(String segmentName) {
    
    this.segmentName = segmentName;
    return this;
  }

   /**
   * Export all devices belonging to the segment.
   * @return segmentName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Export all devices belonging to the segment.")

  public String getSegmentName() {
    return segmentName;
  }


  public void setSegmentName(String segmentName) {
    this.segmentName = segmentName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExportSubscriptionsRequestBody exportSubscriptionsRequestBody = (ExportSubscriptionsRequestBody) o;
    return Objects.equals(this.extraFields, exportSubscriptionsRequestBody.extraFields) &&
        Objects.equals(this.lastActiveSince, exportSubscriptionsRequestBody.lastActiveSince) &&
        Objects.equals(this.segmentName, exportSubscriptionsRequestBody.segmentName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(extraFields, lastActiveSince, segmentName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExportSubscriptionsRequestBody {\n");
    sb.append("    extraFields: ").append(toIndentedString(extraFields)).append("\n");
    sb.append("    lastActiveSince: ").append(toIndentedString(lastActiveSince)).append("\n");
    sb.append("    segmentName: ").append(toIndentedString(segmentName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("extra_fields");
    openapiFields.add("last_active_since");
    openapiFields.add("segment_name");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ExportSubscriptionsRequestBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ExportSubscriptionsRequestBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ExportSubscriptionsRequestBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ExportSubscriptionsRequestBody.class));

       return (TypeAdapter<T>) new TypeAdapter<ExportSubscriptionsRequestBody>() {
           @Override
           public void write(JsonWriter out, ExportSubscriptionsRequestBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ExportSubscriptionsRequestBody read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();

             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ExportSubscriptionsRequestBody given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ExportSubscriptionsRequestBody
  * @throws IOException if the JSON string is invalid with respect to ExportSubscriptionsRequestBody
  */
  public static ExportSubscriptionsRequestBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ExportSubscriptionsRequestBody.class);
  }

 /**
  * Convert an instance of ExportSubscriptionsRequestBody to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

