/*
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.0.1
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onesignal.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.onesignal.client.model.Filter;
import com.onesignal.client.model.Operator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.io.Serializable;

import javax.ws.rs.core.GenericType;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;

import com.onesignal.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-13T23:45:41.211Z[Etc/UTC]")
public class FilterExpression extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(FilterExpression.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!FilterExpression.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'FilterExpression' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);

            final TypeAdapter<Filter> adapterFilter = gson.getDelegateAdapter(this, TypeToken.get(Filter.class));
            final TypeAdapter<Operator> adapterOperator = gson.getDelegateAdapter(this, TypeToken.get(Operator.class));

            return (TypeAdapter<T>) new TypeAdapter<FilterExpression>() {
                @Override
                public void write(JsonWriter out, FilterExpression value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `Filter`
                    if (value.getActualInstance() instanceof Filter) {
                        JsonObject obj = adapterFilter.toJsonTree((Filter)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    // check if the actual instance is of the type `Operator`
                    if (value.getActualInstance() instanceof Operator) {
                        JsonObject obj = adapterOperator.toJsonTree((Operator)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: Filter, Operator");
                }

                @Override
                public FilterExpression read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonObject jsonObject = elementAdapter.read(in).getAsJsonObject();

                    TypeAdapter actualAdapter = adapterFilter;
                    FilterExpression ret = new FilterExpression();
                    ret.setActualInstance(actualAdapter.fromJsonTree(jsonObject));
                    return ret;
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, GenericType> schemas = new HashMap<String, GenericType>();

    public FilterExpression() {
        super("oneOf", Boolean.FALSE);
    }

    public FilterExpression(Filter o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public FilterExpression(Operator o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("Filter", new GenericType<Filter>() {
        });
        schemas.put("Operator", new GenericType<Operator>() {
        });
    }

    @Override
    public Map<String, GenericType> getSchemas() {
        return FilterExpression.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * Filter, Operator
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof Filter) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof Operator) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be Filter, Operator");
    }

    /**
     * Get the actual instance, which can be the following:
     * Filter, Operator
     *
     * @return The actual instance (Filter, Operator)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `Filter`. If the actual instance is not `Filter`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Filter`
     * @throws ClassCastException if the instance is not `Filter`
     */
    public Filter getFilter() throws ClassCastException {
        return (Filter)super.getActualInstance();
    }

    /**
     * Get the actual instance of `Operator`. If the actual instance is not `Operator`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Operator`
     * @throws ClassCastException if the instance is not `Operator`
     */
    public Operator getOperator() throws ClassCastException {
        return (Operator)super.getActualInstance();
    }


 /**
  * Create an instance of FilterExpression given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of FilterExpression
  * @throws IOException if the JSON string is invalid with respect to FilterExpression
  */
  public static FilterExpression fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FilterExpression.class);
  }

 /**
  * Convert an instance of FilterExpression to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

