/*
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onesignal.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.onesignal.client.JSON;

/**
 * InlineResponse2003
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-16T19:49:36.601Z[Etc/UTC]")
public class InlineResponse2003 {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_IN_APP_MESSAGES = "in_app_messages";
  @SerializedName(SERIALIZED_NAME_IN_APP_MESSAGES)
  private List<Object> inAppMessages = null;

  public InlineResponse2003() { 
  }

  public InlineResponse2003 inAppMessages(List<Object> inAppMessages) {
    
    this.inAppMessages = inAppMessages;
    return this;
  }

  public InlineResponse2003 addInAppMessagesItem(Object inAppMessagesItem) {
    if (this.inAppMessages == null) {
      this.inAppMessages = new ArrayList<>();
    }
    this.inAppMessages.add(inAppMessagesItem);
    return this;
  }

   /**
   * Get inAppMessages
   * @return inAppMessages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Object> getInAppMessages() {
    return inAppMessages;
  }


  public void setInAppMessages(List<Object> inAppMessages) {
    this.inAppMessages = inAppMessages;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2003 inlineResponse2003 = (InlineResponse2003) o;
    return Objects.equals(this.inAppMessages, inlineResponse2003.inAppMessages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inAppMessages);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2003 {\n");
    sb.append("    inAppMessages: ").append(toIndentedString(inAppMessages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("in_app_messages");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InlineResponse2003.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InlineResponse2003' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InlineResponse2003> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InlineResponse2003.class));

       return (TypeAdapter<T>) new TypeAdapter<InlineResponse2003>() {
           @Override
           public void write(JsonWriter out, InlineResponse2003 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public InlineResponse2003 read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();

             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of InlineResponse2003 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of InlineResponse2003
  * @throws IOException if the JSON string is invalid with respect to InlineResponse2003
  */
  public static InlineResponse2003 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InlineResponse2003.class);
  }

 /**
  * Convert an instance of InlineResponse2003 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

