/*
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onesignal.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.onesignal.client.model.JourneyEventAttribute;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.onesignal.client.JSON;

/**
 * The journey entry audience. The kind field selects which other fields apply.
 */
@ApiModel(description = "The journey entry audience. The kind field selects which other fields apply.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class JourneyAudience {
  private static final long serialVersionUID = 1L;

  /**
   * Audience kind. Selects which other fields apply.
   */
  @JsonAdapter(KindEnum.Adapter.class)
  public enum KindEnum {
    SEGMENT("segment"),
    
    EVENT_TRIGGER("event_trigger");

    private String value;

    KindEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static KindEnum fromValue(String value) {
      for (KindEnum b : KindEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<KindEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final KindEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public KindEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return KindEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_KIND = "kind";
  @SerializedName(SERIALIZED_NAME_KIND)
  private KindEnum kind;

  public static final String SERIALIZED_NAME_INCLUDED_SEGMENT_IDS = "included_segment_ids";
  @SerializedName(SERIALIZED_NAME_INCLUDED_SEGMENT_IDS)
  private List<String> includedSegmentIds = null;

  public static final String SERIALIZED_NAME_EXCLUDED_SEGMENT_IDS = "excluded_segment_ids";
  @SerializedName(SERIALIZED_NAME_EXCLUDED_SEGMENT_IDS)
  private List<String> excludedSegmentIds = null;

  public static final String SERIALIZED_NAME_FUTURE_ADDITIONS_ONLY = "future_additions_only";
  @SerializedName(SERIALIZED_NAME_FUTURE_ADDITIONS_ONLY)
  private Boolean futureAdditionsOnly;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  private List<List<JourneyEventAttribute>> attributes = null;

  public JourneyAudience() { 
  }

  public JourneyAudience kind(KindEnum kind) {
    
    this.kind = kind;
    return this;
  }

   /**
   * Audience kind. Selects which other fields apply.
   * @return kind
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Audience kind. Selects which other fields apply.")

  public KindEnum getKind() {
    return kind;
  }


  public void setKind(KindEnum kind) {
    this.kind = kind;
  }


  public JourneyAudience includedSegmentIds(List<String> includedSegmentIds) {
    
    this.includedSegmentIds = includedSegmentIds;
    return this;
  }

  public JourneyAudience addIncludedSegmentIdsItem(String includedSegmentIdsItem) {
    if (this.includedSegmentIds == null) {
      this.includedSegmentIds = new ArrayList<>();
    }
    this.includedSegmentIds.add(includedSegmentIdsItem);
    return this;
  }

   /**
   * segment audiences: Segment UUIDs whose users enter the journey.
   * @return includedSegmentIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "segment audiences: Segment UUIDs whose users enter the journey.")

  public List<String> getIncludedSegmentIds() {
    return includedSegmentIds;
  }


  public void setIncludedSegmentIds(List<String> includedSegmentIds) {
    this.includedSegmentIds = includedSegmentIds;
  }


  public JourneyAudience excludedSegmentIds(List<String> excludedSegmentIds) {
    
    this.excludedSegmentIds = excludedSegmentIds;
    return this;
  }

  public JourneyAudience addExcludedSegmentIdsItem(String excludedSegmentIdsItem) {
    if (this.excludedSegmentIds == null) {
      this.excludedSegmentIds = new ArrayList<>();
    }
    this.excludedSegmentIds.add(excludedSegmentIdsItem);
    return this;
  }

   /**
   * segment audiences: Segment UUIDs whose users are excluded.
   * @return excludedSegmentIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "segment audiences: Segment UUIDs whose users are excluded.")

  public List<String> getExcludedSegmentIds() {
    return excludedSegmentIds;
  }


  public void setExcludedSegmentIds(List<String> excludedSegmentIds) {
    this.excludedSegmentIds = excludedSegmentIds;
  }


  public JourneyAudience futureAdditionsOnly(Boolean futureAdditionsOnly) {
    
    this.futureAdditionsOnly = futureAdditionsOnly;
    return this;
  }

   /**
   * segment audiences: when true, only users who newly match the segment after activation enter the journey. Defaults to false.
   * @return futureAdditionsOnly
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "segment audiences: when true, only users who newly match the segment after activation enter the journey. Defaults to false.")

  public Boolean getFutureAdditionsOnly() {
    return futureAdditionsOnly;
  }


  public void setFutureAdditionsOnly(Boolean futureAdditionsOnly) {
    this.futureAdditionsOnly = futureAdditionsOnly;
  }


  public JourneyAudience name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * event_trigger audiences: event name that triggers entry, up to 255 characters.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "event_trigger audiences: event name that triggers entry, up to 255 characters.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public JourneyAudience attributes(List<List<JourneyEventAttribute>> attributes) {
    
    this.attributes = attributes;
    return this;
  }

  public JourneyAudience addAttributesItem(List<JourneyEventAttribute> attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Event attribute matchers, as a list of condition groups. Send a single group whose conditions are AND&#39;d together. More than one group is rejected.
   * @return attributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Event attribute matchers, as a list of condition groups. Send a single group whose conditions are AND'd together. More than one group is rejected.")

  public List<List<JourneyEventAttribute>> getAttributes() {
    return attributes;
  }


  public void setAttributes(List<List<JourneyEventAttribute>> attributes) {
    this.attributes = attributes;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JourneyAudience journeyAudience = (JourneyAudience) o;
    return Objects.equals(this.kind, journeyAudience.kind) &&
        Objects.equals(this.includedSegmentIds, journeyAudience.includedSegmentIds) &&
        Objects.equals(this.excludedSegmentIds, journeyAudience.excludedSegmentIds) &&
        Objects.equals(this.futureAdditionsOnly, journeyAudience.futureAdditionsOnly) &&
        Objects.equals(this.name, journeyAudience.name) &&
        Objects.equals(this.attributes, journeyAudience.attributes);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(kind, includedSegmentIds, excludedSegmentIds, futureAdditionsOnly, name, attributes);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JourneyAudience {\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    includedSegmentIds: ").append(toIndentedString(includedSegmentIds)).append("\n");
    sb.append("    excludedSegmentIds: ").append(toIndentedString(excludedSegmentIds)).append("\n");
    sb.append("    futureAdditionsOnly: ").append(toIndentedString(futureAdditionsOnly)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("kind");
    openapiFields.add("included_segment_ids");
    openapiFields.add("excluded_segment_ids");
    openapiFields.add("future_additions_only");
    openapiFields.add("name");
    openapiFields.add("attributes");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("kind");
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!JourneyAudience.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'JourneyAudience' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<JourneyAudience> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(JourneyAudience.class));

       return (TypeAdapter<T>) new TypeAdapter<JourneyAudience>() {
           @Override
           public void write(JsonWriter out, JourneyAudience value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public JourneyAudience read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();

             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of JourneyAudience given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of JourneyAudience
  * @throws IOException if the JSON string is invalid with respect to JourneyAudience
  */
  public static JourneyAudience fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, JourneyAudience.class);
  }

 /**
  * Convert an instance of JourneyAudience to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

