/*
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onesignal.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.onesignal.client.model.JourneyTimePoint;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.onesignal.client.JSON;

/**
 * A wall-clock window. Each window must span at least 15 minutes.
 */
@ApiModel(description = "A wall-clock window. Each window must span at least 15 minutes.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class JourneyTimeWindow {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_START = "start";
  @SerializedName(SERIALIZED_NAME_START)
  private JourneyTimePoint start;

  public static final String SERIALIZED_NAME_END = "end";
  @SerializedName(SERIALIZED_NAME_END)
  private JourneyTimePoint end;

  public static final String SERIALIZED_NAME_DAY_OF_WEEK = "day_of_week";
  @SerializedName(SERIALIZED_NAME_DAY_OF_WEEK)
  private Integer dayOfWeek;

  public JourneyTimeWindow() { 
  }

  public JourneyTimeWindow start(JourneyTimePoint start) {
    
    this.start = start;
    return this;
  }

   /**
   * When the window opens.
   * @return start
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "When the window opens.")

  public JourneyTimePoint getStart() {
    return start;
  }


  public void setStart(JourneyTimePoint start) {
    this.start = start;
  }


  public JourneyTimeWindow end(JourneyTimePoint end) {
    
    this.end = end;
    return this;
  }

   /**
   * When the window closes.
   * @return end
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "When the window closes.")

  public JourneyTimePoint getEnd() {
    return end;
  }


  public void setEnd(JourneyTimePoint end) {
    this.end = end;
  }


  public JourneyTimeWindow dayOfWeek(Integer dayOfWeek) {
    
    this.dayOfWeek = dayOfWeek;
    return this;
  }

   /**
   * Day of week, 1 &#x3D; Monday. Omit to apply the window to every day.
   * minimum: 1
   * maximum: 7
   * @return dayOfWeek
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Day of week, 1 = Monday. Omit to apply the window to every day.")

  public Integer getDayOfWeek() {
    return dayOfWeek;
  }


  public void setDayOfWeek(Integer dayOfWeek) {
    this.dayOfWeek = dayOfWeek;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JourneyTimeWindow journeyTimeWindow = (JourneyTimeWindow) o;
    return Objects.equals(this.start, journeyTimeWindow.start) &&
        Objects.equals(this.end, journeyTimeWindow.end) &&
        Objects.equals(this.dayOfWeek, journeyTimeWindow.dayOfWeek);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(start, end, dayOfWeek);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JourneyTimeWindow {\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    dayOfWeek: ").append(toIndentedString(dayOfWeek)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("start");
    openapiFields.add("end");
    openapiFields.add("day_of_week");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!JourneyTimeWindow.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'JourneyTimeWindow' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<JourneyTimeWindow> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(JourneyTimeWindow.class));

       return (TypeAdapter<T>) new TypeAdapter<JourneyTimeWindow>() {
           @Override
           public void write(JsonWriter out, JourneyTimeWindow value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public JourneyTimeWindow read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();

             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of JourneyTimeWindow given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of JourneyTimeWindow
  * @throws IOException if the JSON string is invalid with respect to JourneyTimeWindow
  */
  public static JourneyTimeWindow fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, JourneyTimeWindow.class);
  }

 /**
  * Convert an instance of JourneyTimeWindow to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

