/*
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onesignal.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.onesignal.client.model.JourneyListItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.onesignal.client.JSON;

/**
 * JourneyListResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class JourneyListResponse {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_JOURNEYS = "journeys";
  @SerializedName(SERIALIZED_NAME_JOURNEYS)
  private List<JourneyListItem> journeys = null;

  public static final String SERIALIZED_NAME_HAS_MORE = "has_more";
  @SerializedName(SERIALIZED_NAME_HAS_MORE)
  private Boolean hasMore;

  public static final String SERIALIZED_NAME_NEXT_CURSOR = "next_cursor";
  @SerializedName(SERIALIZED_NAME_NEXT_CURSOR)
  private String nextCursor;

  public JourneyListResponse() { 
  }

  public JourneyListResponse journeys(List<JourneyListItem> journeys) {
    
    this.journeys = journeys;
    return this;
  }

  public JourneyListResponse addJourneysItem(JourneyListItem journeysItem) {
    if (this.journeys == null) {
      this.journeys = new ArrayList<>();
    }
    this.journeys.add(journeysItem);
    return this;
  }

   /**
   * Journeys ordered by creation time, newest first.
   * @return journeys
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Journeys ordered by creation time, newest first.")

  public List<JourneyListItem> getJourneys() {
    return journeys;
  }


  public void setJourneys(List<JourneyListItem> journeys) {
    this.journeys = journeys;
  }


  public JourneyListResponse hasMore(Boolean hasMore) {
    
    this.hasMore = hasMore;
    return this;
  }

   /**
   * true if more journeys exist beyond this page.
   * @return hasMore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "true if more journeys exist beyond this page.")

  public Boolean getHasMore() {
    return hasMore;
  }


  public void setHasMore(Boolean hasMore) {
    this.hasMore = hasMore;
  }


  public JourneyListResponse nextCursor(String nextCursor) {
    
    this.nextCursor = nextCursor;
    return this;
  }

   /**
   * Cursor for the next page. Present only when has_more is true.
   * @return nextCursor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Cursor for the next page. Present only when has_more is true.")

  public String getNextCursor() {
    return nextCursor;
  }


  public void setNextCursor(String nextCursor) {
    this.nextCursor = nextCursor;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JourneyListResponse journeyListResponse = (JourneyListResponse) o;
    return Objects.equals(this.journeys, journeyListResponse.journeys) &&
        Objects.equals(this.hasMore, journeyListResponse.hasMore) &&
        Objects.equals(this.nextCursor, journeyListResponse.nextCursor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(journeys, hasMore, nextCursor);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JourneyListResponse {\n");
    sb.append("    journeys: ").append(toIndentedString(journeys)).append("\n");
    sb.append("    hasMore: ").append(toIndentedString(hasMore)).append("\n");
    sb.append("    nextCursor: ").append(toIndentedString(nextCursor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("journeys");
    openapiFields.add("has_more");
    openapiFields.add("next_cursor");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!JourneyListResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'JourneyListResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<JourneyListResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(JourneyListResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<JourneyListResponse>() {
           @Override
           public void write(JsonWriter out, JourneyListResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public JourneyListResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();

             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of JourneyListResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of JourneyListResponse
  * @throws IOException if the JSON string is invalid with respect to JourneyListResponse
  */
  public static JourneyListResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, JourneyListResponse.class);
  }

 /**
  * Convert an instance of JourneyListResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

