/*
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onesignal.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.onesignal.client.model.JourneyMessageStats;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.onesignal.client.JSON;

/**
 * Stats for a single node. Keyed in the response by the node&#39;s server-assigned id.
 */
@ApiModel(description = "Stats for a single node. Keyed in the response by the node's server-assigned id.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class JourneyNodeStats {
  private static final long serialVersionUID = 1L;

  /**
   * Node kind, repeated here so stats can be read without joining against the journey definition.
   */
  @JsonAdapter(KindEnum.Adapter.class)
  public enum KindEnum {
    WAIT("wait"),
    
    TIME_WINDOW("time_window"),
    
    SEND_PUSH("send_push"),
    
    SEND_EMAIL("send_email"),
    
    SEND_SMS("send_sms"),
    
    SEND_IAM("send_iam"),
    
    SEND_WEBHOOK("send_webhook"),
    
    TAG("tag"),
    
    SPLIT_RANGE("split_range"),
    
    YES_NO("yes_no"),
    
    WAIT_UNTIL("wait_until");

    private String value;

    KindEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static KindEnum fromValue(String value) {
      for (KindEnum b : KindEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<KindEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final KindEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public KindEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return KindEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_KIND = "kind";
  @SerializedName(SERIALIZED_NAME_KIND)
  private KindEnum kind;

  public static final String SERIALIZED_NAME_WAITING = "waiting";
  @SerializedName(SERIALIZED_NAME_WAITING)
  private Integer waiting;

  public static final String SERIALIZED_NAME_COMPLETED = "completed";
  @SerializedName(SERIALIZED_NAME_COMPLETED)
  private Integer completed;

  public static final String SERIALIZED_NAME_EXITED_EARLY = "exited_early";
  @SerializedName(SERIALIZED_NAME_EXITED_EARLY)
  private Integer exitedEarly;

  public static final String SERIALIZED_NAME_MESSAGE_STATS = "message_stats";
  @SerializedName(SERIALIZED_NAME_MESSAGE_STATS)
  private JourneyMessageStats messageStats;

  public JourneyNodeStats() { 
  }

  public JourneyNodeStats kind(KindEnum kind) {
    
    this.kind = kind;
    return this;
  }

   /**
   * Node kind, repeated here so stats can be read without joining against the journey definition.
   * @return kind
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Node kind, repeated here so stats can be read without joining against the journey definition.")

  public KindEnum getKind() {
    return kind;
  }


  public void setKind(KindEnum kind) {
    this.kind = kind;
  }


  public JourneyNodeStats waiting(Integer waiting) {
    
    this.waiting = waiting;
    return this;
  }

   /**
   * Users currently held at this node.
   * @return waiting
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Users currently held at this node.")

  public Integer getWaiting() {
    return waiting;
  }


  public void setWaiting(Integer waiting) {
    this.waiting = waiting;
  }


  public JourneyNodeStats completed(Integer completed) {
    
    this.completed = completed;
    return this;
  }

   /**
   * Users who advanced past this node normally.
   * @return completed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Users who advanced past this node normally.")

  public Integer getCompleted() {
    return completed;
  }


  public void setCompleted(Integer completed) {
    this.completed = completed;
  }


  public JourneyNodeStats exitedEarly(Integer exitedEarly) {
    
    this.exitedEarly = exitedEarly;
    return this;
  }

   /**
   * Users who left the journey from this node through an early exit rule.
   * @return exitedEarly
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Users who left the journey from this node through an early exit rule.")

  public Integer getExitedEarly() {
    return exitedEarly;
  }


  public void setExitedEarly(Integer exitedEarly) {
    this.exitedEarly = exitedEarly;
  }


  public JourneyNodeStats messageStats(JourneyMessageStats messageStats) {
    
    this.messageStats = messageStats;
    return this;
  }

   /**
   * Get messageStats
   * @return messageStats
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public JourneyMessageStats getMessageStats() {
    return messageStats;
  }


  public void setMessageStats(JourneyMessageStats messageStats) {
    this.messageStats = messageStats;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JourneyNodeStats journeyNodeStats = (JourneyNodeStats) o;
    return Objects.equals(this.kind, journeyNodeStats.kind) &&
        Objects.equals(this.waiting, journeyNodeStats.waiting) &&
        Objects.equals(this.completed, journeyNodeStats.completed) &&
        Objects.equals(this.exitedEarly, journeyNodeStats.exitedEarly) &&
        Objects.equals(this.messageStats, journeyNodeStats.messageStats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kind, waiting, completed, exitedEarly, messageStats);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JourneyNodeStats {\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    waiting: ").append(toIndentedString(waiting)).append("\n");
    sb.append("    completed: ").append(toIndentedString(completed)).append("\n");
    sb.append("    exitedEarly: ").append(toIndentedString(exitedEarly)).append("\n");
    sb.append("    messageStats: ").append(toIndentedString(messageStats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("kind");
    openapiFields.add("waiting");
    openapiFields.add("completed");
    openapiFields.add("exited_early");
    openapiFields.add("message_stats");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!JourneyNodeStats.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'JourneyNodeStats' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<JourneyNodeStats> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(JourneyNodeStats.class));

       return (TypeAdapter<T>) new TypeAdapter<JourneyNodeStats>() {
           @Override
           public void write(JsonWriter out, JourneyNodeStats value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public JourneyNodeStats read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();

             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of JourneyNodeStats given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of JourneyNodeStats
  * @throws IOException if the JSON string is invalid with respect to JourneyNodeStats
  */
  public static JourneyNodeStats fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, JourneyNodeStats.class);
  }

 /**
  * Convert an instance of JourneyNodeStats to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

