/*
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onesignal.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.onesignal.client.model.JourneyAudience;
import com.onesignal.client.model.JourneyEarlyExit;
import com.onesignal.client.model.JourneyNode;
import com.onesignal.client.model.JourneyReentryRules;
import com.onesignal.client.model.JourneySchedule;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.onesignal.client.JSON;

/**
 * Partial update applied with JSON Merge Patch (RFC 7396). Send only the fields you want to change. A null value clears a nullable field. Arrays such as nodes are replaced wholesale.
 */
@ApiModel(description = "Partial update applied with JSON Merge Patch (RFC 7396). Send only the fields you want to change. A null value clears a nullable field. Arrays such as nodes are replaced wholesale.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class UpdateJourneyRequest {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_AUDIENCE = "audience";
  @SerializedName(SERIALIZED_NAME_AUDIENCE)
  private JourneyAudience audience;

  public static final String SERIALIZED_NAME_EARLY_EXIT = "early_exit";
  @SerializedName(SERIALIZED_NAME_EARLY_EXIT)
  private JourneyEarlyExit earlyExit;

  public static final String SERIALIZED_NAME_REENTRY_RULES = "reentry_rules";
  @SerializedName(SERIALIZED_NAME_REENTRY_RULES)
  private JourneyReentryRules reentryRules;

  public static final String SERIALIZED_NAME_SCHEDULE = "schedule";
  @SerializedName(SERIALIZED_NAME_SCHEDULE)
  private JourneySchedule schedule;

  public static final String SERIALIZED_NAME_NODES = "nodes";
  @SerializedName(SERIALIZED_NAME_NODES)
  private List<JourneyNode> nodes = null;

  /**
   * Target state. Set active to activate a draft journey, or scheduled together with a future schedule.start_at to activate it later. Set archived to stop a running journey; archiving is permanent. Only scheduled and processing journeys can return to draft.
   */
  @JsonAdapter(StateEnum.Adapter.class)
  public enum StateEnum {
    DRAFT("draft"),
    
    SCHEDULED("scheduled"),
    
    ACTIVE("active"),
    
    ARCHIVED("archived");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StateEnum fromValue(String value) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StateEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StateEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StateEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  private StateEnum state;

  public static final String SERIALIZED_NAME_CONCURRENCY_KEY = "concurrency_key";
  @SerializedName(SERIALIZED_NAME_CONCURRENCY_KEY)
  private String concurrencyKey;

  public UpdateJourneyRequest() { 
  }

  public UpdateJourneyRequest name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Journey name.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Journey name.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public UpdateJourneyRequest description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Journey description. Send null to clear it.
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Journey description. Send null to clear it.")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public UpdateJourneyRequest audience(JourneyAudience audience) {
    
    this.audience = audience;
    return this;
  }

   /**
   * Get audience
   * @return audience
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public JourneyAudience getAudience() {
    return audience;
  }


  public void setAudience(JourneyAudience audience) {
    this.audience = audience;
  }


  public UpdateJourneyRequest earlyExit(JourneyEarlyExit earlyExit) {
    
    this.earlyExit = earlyExit;
    return this;
  }

   /**
   * Get earlyExit
   * @return earlyExit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public JourneyEarlyExit getEarlyExit() {
    return earlyExit;
  }


  public void setEarlyExit(JourneyEarlyExit earlyExit) {
    this.earlyExit = earlyExit;
  }


  public UpdateJourneyRequest reentryRules(JourneyReentryRules reentryRules) {
    
    this.reentryRules = reentryRules;
    return this;
  }

   /**
   * Get reentryRules
   * @return reentryRules
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public JourneyReentryRules getReentryRules() {
    return reentryRules;
  }


  public void setReentryRules(JourneyReentryRules reentryRules) {
    this.reentryRules = reentryRules;
  }


  public UpdateJourneyRequest schedule(JourneySchedule schedule) {
    
    this.schedule = schedule;
    return this;
  }

   /**
   * Get schedule
   * @return schedule
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public JourneySchedule getSchedule() {
    return schedule;
  }


  public void setSchedule(JourneySchedule schedule) {
    this.schedule = schedule;
  }


  public UpdateJourneyRequest nodes(List<JourneyNode> nodes) {
    
    this.nodes = nodes;
    return this;
  }

  public UpdateJourneyRequest addNodesItem(JourneyNode nodesItem) {
    if (this.nodes == null) {
      this.nodes = new ArrayList<>();
    }
    this.nodes.add(nodesItem);
    return this;
  }

   /**
   * Full ordered list of nodes, which replaces the existing graph wholesale. Preserve each node&#39;s server-assigned id from a prior fetch to keep in-flight users on that node; omit id to add a new node.
   * @return nodes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Full ordered list of nodes, which replaces the existing graph wholesale. Preserve each node's server-assigned id from a prior fetch to keep in-flight users on that node; omit id to add a new node.")

  public List<JourneyNode> getNodes() {
    return nodes;
  }


  public void setNodes(List<JourneyNode> nodes) {
    this.nodes = nodes;
  }


  public UpdateJourneyRequest state(StateEnum state) {
    
    this.state = state;
    return this;
  }

   /**
   * Target state. Set active to activate a draft journey, or scheduled together with a future schedule.start_at to activate it later. Set archived to stop a running journey; archiving is permanent. Only scheduled and processing journeys can return to draft.
   * @return state
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Target state. Set active to activate a draft journey, or scheduled together with a future schedule.start_at to activate it later. Set archived to stop a running journey; archiving is permanent. Only scheduled and processing journeys can return to draft.")

  public StateEnum getState() {
    return state;
  }


  public void setState(StateEnum state) {
    this.state = state;
  }


  public UpdateJourneyRequest concurrencyKey(String concurrencyKey) {
    
    this.concurrencyKey = concurrencyKey;
    return this;
  }

   /**
   * Optional optimistic-concurrency token. Pass the concurrency_key from a prior fetch to reject the update with 409 if the journey changed. Omit to skip the check.
   * @return concurrencyKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Optional optimistic-concurrency token. Pass the concurrency_key from a prior fetch to reject the update with 409 if the journey changed. Omit to skip the check.")

  public String getConcurrencyKey() {
    return concurrencyKey;
  }


  public void setConcurrencyKey(String concurrencyKey) {
    this.concurrencyKey = concurrencyKey;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateJourneyRequest updateJourneyRequest = (UpdateJourneyRequest) o;
    return Objects.equals(this.name, updateJourneyRequest.name) &&
        Objects.equals(this.description, updateJourneyRequest.description) &&
        Objects.equals(this.audience, updateJourneyRequest.audience) &&
        Objects.equals(this.earlyExit, updateJourneyRequest.earlyExit) &&
        Objects.equals(this.reentryRules, updateJourneyRequest.reentryRules) &&
        Objects.equals(this.schedule, updateJourneyRequest.schedule) &&
        Objects.equals(this.nodes, updateJourneyRequest.nodes) &&
        Objects.equals(this.state, updateJourneyRequest.state) &&
        Objects.equals(this.concurrencyKey, updateJourneyRequest.concurrencyKey);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, audience, earlyExit, reentryRules, schedule, nodes, state, concurrencyKey);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateJourneyRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    audience: ").append(toIndentedString(audience)).append("\n");
    sb.append("    earlyExit: ").append(toIndentedString(earlyExit)).append("\n");
    sb.append("    reentryRules: ").append(toIndentedString(reentryRules)).append("\n");
    sb.append("    schedule: ").append(toIndentedString(schedule)).append("\n");
    sb.append("    nodes: ").append(toIndentedString(nodes)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    concurrencyKey: ").append(toIndentedString(concurrencyKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("description");
    openapiFields.add("audience");
    openapiFields.add("early_exit");
    openapiFields.add("reentry_rules");
    openapiFields.add("schedule");
    openapiFields.add("nodes");
    openapiFields.add("state");
    openapiFields.add("concurrency_key");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateJourneyRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateJourneyRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateJourneyRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateJourneyRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateJourneyRequest>() {
           @Override
           public void write(JsonWriter out, UpdateJourneyRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateJourneyRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();

             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UpdateJourneyRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UpdateJourneyRequest
  * @throws IOException if the JSON string is invalid with respect to UpdateJourneyRequest
  */
  public static UpdateJourneyRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateJourneyRequest.class);
  }

 /**
  * Convert an instance of UpdateJourneyRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

